resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node will do a GPS location reverse lookup and return the
      associated address with a location.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryWorkflowsNodesAddressLookup~
    name: Address Lookup
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - gps
      - address
version: 1
