resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Includes implementations for 404 and 500 error pages.
    filesPath: ./files
    globals: []
    id: ~losant-application-libraryExperiencesPagesUserFriendlyErrorPages-0~
    name: User-Friendly Error Pages
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - "404"
      - "500"
      - error
      - uncaught
      - exception
      - catch
version: 1
