resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Displays a filterable dropdown menu for use in forms or for navigation.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryExperiencesComponentsAdvancedDropdown~
    name: Advanced Dropdown
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - dropdown
      - select
      - devices
      - form
      - navigation
version: 1
