resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: The Aruba Meridian indoor asset tracking tag.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-libraryDevicesRecipesArubaMeridianAssetTag~
    name: Aruba Meridian Asset Tag
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - aruba
      - meridian
      - asset
      - tag
      - tracking
      - indoor
version: 1
