resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This node provides the ability to report a SIGNL4 event via the SIGNL4 API.
    filesPath: ./files
    globals: []
    id: ~losant-application-libraryWorkflowsNodesSignl4Alert-0~
    name: SIGNL4 Alert
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - notifications
      - alerting
      - signl4
version: 1
