resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: RuuviTag open-source wireless sensor node.
    filesPath: ./files
    globals: []
    id: ~losant-application-libraryDevicesRecipesRuuviTag-0~
    name: RuuviTag
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - ruuvi
      - ble
version: 1
