resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template demonstrates the use of an on-disk workflow to enable
      an Edge Agent to register itself as a new device.
    filesPath: ./files
    globals: []
    id: ~losant-application-libraryWorkflowsEdgeComputeEdgeAgentAutoRegistration-0~
    name: Edge Agent Auto Registration
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - register
      - registration
      - provision
      - edge
      - gateway
version: 1
