resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: This template demonstrates how to authenticate to an Experience
      using Single Sign-On (SSO) with Azure Active Directory.
    filesPath: ./files
    globals:
      - cloudOnly: true
        description: ""
        json: '"identityProviderMetadataTemplate"'
        key: identityProviderMetadataTemplate_example_com
      - cloudOnly: true
        description: ""
        json: '"serviceProviderMetadataTemplate"'
        key: serviceProviderMetadataTemplate_example_com
    id: ~exportplaceholderid-application-libraryExperiencesFormsAzureActiveDirectorySso~
    name: Azure Active Directory SSO
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - sso
      - azure
      - active-directory
      - single-sign-on
      - saml
version: 1
