resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: A multi-tenant equipment monitoring application with multiple
      customers and users.
    filesPath: ./files
    globals: []
    id: ~exportplaceholderid-application-applicationIndustrialEquipmentMonitor~
    name: Industrial Equipment Monitor
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords: []
version: 1
