resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: "This template demonstrates how to use AI to perform real-time
      outlier detection using a model trained and executed with Elipsa. "
    filesPath: ./files
    globals:
      - cloudOnly: false
        description: ""
        json: '"https://api.elipsa.ai:9090/graphdb/api/v1.0/ml/scenario/predictions/e9972e98-51c9-11eb-9485-0acec021ad7c"'
        key: elipsa_api
    id: ~losant-application-applicationElipsaPredictiveMaintenance-0~
    name: Elipsa Predictive Maintenance
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords: []
version: 1
