resourceType: Application
resources:
  - blobUrlTTL: 86400
    description: Display values of device tags and allow experience users to edit them.
    filesPath: ./files
    globals: []
    id: ~losant-application-libraryExperiencesPagesEditDeviceTags-0~
    name: Edit Device Tags
    readmePath: ./README.md
    imagePath: ./preview.png
    authorName: Losant
    authorUrl: https://www.losant.com
    keywords:
      - experience
      - edit-device
      - form
      - validation
version: 1
